### PR TITLE
Make it possible to set more properties using Maven build profiles

### PR DESCRIPTION
**Pull request by heidivanparys**
Properties in configuration.properties in Re3gistry2:

- ~application.status.baseuri~
- SMTP properties, including user and password
- sender mail address for mails

Also fix 2 errors related to application.rooturl.

### CODE REVIEW

**Comment by emanuelaepure10** [comment]
Dear @heidivanparys 

I think that this property
<application.status.baseuri>http://inspire.ec.europa.eu</application.status.baseuri>
that you have added in the pom.xml is already present in the database in the reg_statusgroup table.
You need to be sure that they are the same. Whenever needed I would retrieve it from the database.
What do you think?

Best regards

**Comment by heidivanparys** [comment]
I indeed had to update the database 

```sql
UPDATE reg_statusgroup SET baseuri = 'http://mydomain.dk/registry
```

But property `application.status.baseuri` is taken from the configuration file in one case, shouldn't that be taken from the database (column `reg_statusgroup.baseuri`) then instead?:

image

Also with the current code, configuration.properties contains property `application.status.baseuri`, so also without this pull request, one has to make sure they are the same:

https://github.com/ec-jrc/re3gistry/blob/a813bf42a87211e8196b62d626c7430dbf48d5a8/sources/Re3gistry2/src/main/resources/configurations_files/configuration.properties#L52

Note that https://github.com/ec-jrc/re3gistry/pull/85/files also introduced property `application.status.baseuri`, sorry, I also saw this dependency now.

Perhaps an issue should be created afterwards to remove property `application.status.baseuri` from the configuration.properties files altogether? Including updating method `eu.europa.ec.re3gistry2.javaapi.solr.SolrHandler.indexItem(RegItem, EntityManager)`.

**Comment by emanuelaepure10** [comment]
Indead, I would remove as well the property
application.status.baseuri
and take the baseuri always from the reg_statusgroup table.

**Comment by heidivanparys** [comment]
I merged the master back in, and removed `application.status.baseuri` from the pom again. This should be ready to (squash) merge into master now.

**Pull request merged**
